// <auto-generated />
using CloudComputingAllAboutCat.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudComputingAllAboutCat.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210723010124_Add required fields")]
    partial class Addrequiredfields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CloudComputingAllAboutCat.Model.Fact", b =>
                {
                    b.Property<int>("FactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FactText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FactID");

                    b.ToTable("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
