// <auto-generated />
using CloudComputingAllAboutCat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CloudComputingAllAboutCat.Migrations
{
    [DbContext(typeof(FactDbContext))]
    partial class FactDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CloudComputingAllAboutCat.Models.Fact", b =>
                {
                    b.Property<int>("FactID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FactText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FactID");

                    b.ToTable("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
